### ISSUE TITLE
Migrate to APIv3

### ISSUE THREAD

**Issue by CarlColglazier** [CarlColglazier/tba#4]
First issue to address: backward compatibility. In an ideal world, we could just iterate the version number and everything would be good to go.

A quick fix for now could be to create a different client struct called something like `TBAClient`.

**Comment by CarlColglazier** [comment]
## Backwards Compatibility 

APIv2 will be deprecated at some point next year, which means that eventually users of this library and the library itself will need to migrate to APIv3.

For now, all parts of the APIv2 library will need to be marked as deprecated once APIv3 is supported and then removed entirely when APIv2 itself is deprecated. The Golang blog has a [suggestion](https://blog.golang.org/godoc-documenting-go-code) on how to go about this.

>  Sometimes a struct field, function, type, or even a whole package becomes redundant or unnecessary, but must be kept for compatibility with existing programs. To signal that an identifier should not be used, add a paragraph to its doc comment that begins with "Deprecated:" followed by some information about the deprecation. There are a such few examples in the standard library. 

I think it is possible to maintain backwards compatibility until the point where APIv2 is deprecated. We can offer a different constructor for APIv3 users which continues to use the `Client` struct.

## Design

APIv3 is set up a bit differently compared to APIv2: some requests have modifiers which returns different amounts of data. For example, a request to `api/v3/event/2017nccmp/teams` can be modified by adding `/simple` or `/keys`.

In a discussion with @ErikBoesen, I brought up the idea of using the [builder pattern to construct requests](https://en.wikipedia.org/wiki/Builder_pattern). Under such a design, we could call something like `tba, err := tba.New(<KEY>)`. We could then construct requests using calls like `tba.Event("2017nccmp").Teams().Reqest()`. I will make a second issue to discuss the design in more depth soon.

**Comment by ErikBoesen** [comment]
Completed by #5.
